- _assets/app.less
- _assets/js/upload-demo.js
Refs #25 
(much smoother in real life than captured GIF)
Will think about how to highlight the generated link/button for the newly uploaded file in next PR.
> Demo: animated reset for progress bar upon finishing upload

- package.json
:rocket:
One of your dependencies has just updated, so this PR bumps the corresponding version number in your `package.json`.
You can now check that the dependency update doesn't break your code, and then release the new version of your software safe in the knowledge that it will stay in this working state, regardless of _when_ your users do `$ npm install`.
Have a good day!
---
This pull request was created by [greenkeeper.io](http://greenkeeper.io/).
It keeps your software, up to date, all the time.
<sub>
Tired of seeing this sponsor message? Upgrade to the supporter plan!
You'll also get your pull requests faster :zap:
</sub>
> Updated clean-css to version 3.4.5

- package.json
:rocket:
stylelint just published version 1.2.0, so that’s now up to date in your `package.json`.
Check that it doesn’t break your code and release the new version of your software safe in the knowledge that it will stay in this working state.
---
The new version differs by 11 commits (ahead by 11, behind by 0).
- [a8278fc](https://github.com/stylelint/stylelint/commit/a8278fc2628047d086d832f456e007cfeaa30fde): Prepare 1.2.0
- [761907f](https://github.com/stylelint/stylelint/commit/761907f122f95754feb6180a81c694cabe571deb): Make order of changelog items consistent
- [84bad43](https://github.com/stylelint/stylelint/commit/84bad43407f611bffd0d8768973105e9389b80a2): Ignore order of properties unspecified in user array; provide options to change behavior
- …
> Updated stylelint to version 1.2.0

- package.json
> Remove obsolent dependencies

- unpublished/2015-10-tus.1.0.md
Improved the wording of the tus 1.0 launch post.
> Improved the wording of the tus 1.0 launch post

- implementations.md
> Add cenkalti/tus.py client to implementations list

- implementations.md
Hi! 
I have updated the description of tusdotnet as we have implemented more than the creation extension. :) I'm currently working on concatenation which should be completed as soon as I get the time to complete it :D
Also if you could please rebuild the site after merging this I would be grateful.
> Updated description of tusdotnet as we now support more extensions

- _data/logos.yml
We're implementing tus into our file upload process 👍 🙌
> Added logo for Soundoff.io

- assets/stylesheets/app.css.less
- assets/stylesheets/blog.css.less
- assets/stylesheets/typography.css.less
- blog.md
This is my first pull request for tus! 🎉
- Some paddings for H1s
- Updated font sizes for the headings (for better contrast between them)
- Separate CSS file for typographic styles
- More spacing between blog posts
- Blog: `»Read on` → `Read on »`
> Typography improvements

- _layouts/default.html
- assets/stylesheets/app.css.less
- assets/stylesheets/blog.css.less
- assets/stylesheets/layout.css.less
- assets/stylesheets/typography.css.less
- blog.md
Navbar was broken on mobile. Now, this is fixed:
**Note:** I created this branch from the previous (`typography-tweaks`), and it seems I was wrong because this PR includes commits from that branch. Should I fix it, and if yes, how to do it? All changes we need in this PR are in https://github.com/tus/tus.io/commit/be1a6785ec21171e0a8978e79649b0a953889faa.
> Fix of the broken navbar

- _includes/community.html
- _pages/implementations.md
I changed my username to `janko` today, so just updating the references here.
> Update "janko-m" username to "janko"

- _pages/implementations.md
it is a pure bash implementation of tus 1.0.0 client
> Add adhocore/tusc.sh in community clients section

- _content/implementations.md
Please add new library  to the implementation list.
> https://github.com/pylotcode/aiohttp-tus

- _layouts/default.html
- _posts/2020-05-04-tus-js-client-200.md
- assets/stylesheets/app.css.less
- assets/stylesheets/blog.css.less
- assets/stylesheets/home.css.less
- assets/stylesheets/layout.css.less
- assets/stylesheets/protocol.css.less
- assets/stylesheets/typography.css.less
Polished typography, slightly improved layout, added custom font and fixed some minor issues.
> Design improvements - round one

- _content/implementations.md
Adds the nativescript-tus-client implementation to the community implemementations list.
> Adds the nativescript-tus-client to the implementations list.

- _content/implementations.md
It would be nice if you could add aiotus to the list of community implementations.
> Add the aiotus client-side implementation

- _content/implementations.md
https://app.intercom.com/a/apps/qiqpfgjg/inbox/inbox/all/conversations/26852700005053 I have removed the whole section belonging to jpscaletti/tus as I couldn't find his github anymore.
> remove jpscaletti/tus

- _posts/2016-03-07-tus-s3-backend.md
https://app.intercom.com/a/apps/qiqpfgjg/inbox/inbox/all/conversations/26852700005053 removed vulnerable link, unable to find replacement link.
> remove https://godoc.org/github.com/tus/tusd/s3store link

- _data/press.yml
https://app.intercom.com/a/apps/qiqpfgjg/inbox/inbox/5079389/conversations/26852700005173, no.2i
Removed the t3n press section as the link redirected to a 404 page. I tried to find the article made by the company but I could not find it on their website. Because there is no article, I removed the whole section.
> removed t3n press

- _posts/2015-02-03-protocol-v1.0.0-prerelease.md
https://app.intercom.com/a/apps/qiqpfgjg/inbox/inbox/5079389/conversations/26852700005173, no. 3i
Removed the link as it was vulnerable and could not find a replacement link.
> remove vulnerable link

- _content/home.html
https://app.intercom.com/a/apps/qiqpfgjg/inbox/inbox/5079389/conversations/26852700005173, no.1i
On line 199, the link, "https://transloadit.us1.list-manage.com/subscribe/post?u=98e560c614f2baaf47237f500&amp;id=37aafbe5c1" does not work when it is pressed. It redirects to a 404:Page Not Found. Is there another URL that we can replace it with? If so, I will make the changes for you. I have left a reminder, (need replacement link) on the same line to find it easier.
> update subscribe url

- _content/implementations.md
This commit adds rustus server implementation in the implementations list.
Signed-off-by: Pavel Kirilin <win10@list.ru>
> Added Rustus implementation.

- _content/faq.md
- _content/implementations.md
- _posts/2015-09-19-project-status.md
- _posts/2022-02-24-tus-v2.md
https://app.intercom.com/a/apps/qiqpfgjg/inbox/inbox/5079389/conversations/26852700007145
> Fix broken links

- _content/implementations.md
Meteoritus is a Rust library that implements tus v1.0.0 to integrate resumable upload features to Rocket framework.
> Adding meteoritus implementations

- src/components/ImplementationListItem.astro
- src/content/implementations/tus-android-client.json
- src/content/implementations/tus-java-client.json
- src/content/implementations/tus-js-client.json
- src/content/implementations/tus-node-server.json
- src/content/implementations/tus-py-client.json
- src/content/implementations/tusd.json
- src/content/implementations/tusdotnet.json
- src/content/implementations/tuskit.json
- src/pages/implementations.astro
and update the outdated tus-node-server description.
> Split official implementations into client/server

- src/content/implementations/tus-blazor-client.json
tus-blazor-client is a wrapper library project for tus-js-client that can be used in .NET Blazor.
> Add tus-blazor-client

- src/content/implementations/fastus.json
Thank you again for creating TUS. =)
> Add FasTUS to Community Servers

- src/content/implementations/tus4s.json
Thank you for your work on tus! 🙏🏼
> Add tus4s to the community server implementation list

- src/content/implementations/tus-cpp-client.json
This is my client implementation for cpp
> Tus c++ client implementation

- src/content/blog/2025-05-20-tusd-nixpkgs.md
See https://github.com/tus/tusd/issues/683#issuecomment-2867345991.
> Add blog post announcing tusd in nixpkgs
