_data/logos.yml

Not sure if I got the format of the info right but I'm trying to add SDSC to the list, with a link to the sdsc logo and website.

Add San Diego Supercomputer Center to "who's using tus.io"

---

implementations.md

The existing [Rubytus](https://github.com/picocandy/rubytus) implementation is still far from 1.0.0, and it's using a Ruby web framework which isn't easy to work with, so I created my own Ruby implementation which fully implements tus 1.0.0.
https://github.com/janko-m/tus-ruby-server

Add janko-m/tus-ruby-server for tus 1.0.0

---

_data/logos.yml

We recently implemented tus.io using tus-js and tus-ruby-server to support video file uploads ranging from 50MB to 50GB. The protocol and implementations work perfectly.

Add "90 Seconds" to logos.yml

---

implementations.md

The janko-m/tus-ruby-server repo seemed to be the only one without a bold tech, so I wanted to propose this change for improved readability.

Add emphasis for improved skimability

---

implementations.md

Hi! 
tusdotnet is now feature complete! All major extensions are supported and a new release will hit Nuget in a couple of weeks.
I have updated the description of tusdotnet and also moved the entire repo to its own organization. I have some other stuff in the pipeline that will go into the same organization, e.g. a data store for tusdotnet that saves data to an Azure Storage account. 
What's your policy on using your logo? I was thinking about using it as the tusdotnet organization logo but with a added ".net" text in the lower right corner.

Update description of tusdotnet

---

implementations.md

All implemenations use the "vX.Y.Z" version format, only tus-ruby-server uses "X.Y.Z", so just fixing that.

Fix small inconsistency in tus version format

---

_layouts/default.html
home.html

There was Transloadit instead of tus in the page titles:
It has been fixed.
Also, there was no project name in the homepage title, which I believe is wrong. So I changed it from `Resumable File Uploads` to `tus - resumable file uploads`

Correct page titles

---

implementations.md

The Shrine repository has been moved to the "shrinerb" organization.

Correct link to Shrine

---

_layouts/default.html
assets/stylesheets/blog.css.less
assets/stylesheets/home.css.less
assets/stylesheets/layout.css.less

This PR fixes some problems with fonts. 
Firstly, we couldn't load a font from Typekit and had no fallbacks, so default font was shown:
Also, we have a very thin font style used in the intro section. I replaced it with a more readable one.

Update the font stack

---

_pages/implementations.md

I found that there is currently only one command line tool for TUS (as far as I know). And that is written in python which require python runtime and pip to install. Sometimes, it is more convenient to just download a static binary and then start TUS client or server, also I need a simple file listing page for server (I also saw some request for it) and so here is *tusc*

Add tusc implementation

---

assets/javascripts/upload-demo.js
assets/stylesheets/demo.css.less

Kevin's feedback:
> If i pause the upload, the progress bar still animates. it's not wrong maybe, but i would have expected that froze too then.
Here, it's fixed: the animation freezes on pause, and the green color also dims a little bit. I also set a min-width for progress bar's pause/resume button, so it won't be "jumping" because of the caption changes.
Preview:

Make the paused state clearer

---

_content/implementations.md

It would be great if you can include the tus_client dart library into the list of community implementations:
https://pub.dev/packages/tus_client
https://github.com/jjmutumi/tus_client

Adding tus_client dart library entry

---

_content/implementations.md

* Move tusdotnet from community to official
* Remove an "also" from description of tus-node-server to not be so repetitive when adding tusdotnet (` You can also run this to test client implementations with.` -> ` You can run this to test client implementations with.`
I couldn't get the site to start locally, probably because I'm on Windows. Please let me know if anything is incorect.

Move tusdotnet to official implementations

---

_layouts/protocol.html
assets/stylesheets/layout.scss
assets/stylesheets/protocol.scss

As Kevin mentioned in #174, there is an ugly select in the Protocol page. This is especially relevant to Firefox, where customized selects look really bad.
So, I've reset styles for all `<select>’s` in Firefox, and also slightly polished that particular protocol version select.
Before and after:

Improve the protocol version select, and all selects in general

---

_layouts/default.html
google18275eed01f76b59.html

We're pretty frequently receiving an email regarding mobile usability issues. Not only it's a bit annoying, but I'm afraid it might affect SEO:
Some time ago I noticed that those errors are related to Google's verification HTML file which is very simple and, of course, is not optimized for mobile. Here, I'm trying to use another verification method (meta tag) which allows me to remove the HTML file. Hopefully, it's gonna fix the issue.
**Note:** I'll need to trigger a verification process manually on Google Console after this is merged & deployed.

Use a meta tag instead of a file for Google Site Verification

---

_content/faq.md

I promised I would go through the FAQ once more after Charlie's PR had been merged, so here we go. I did find a number of things to fix still, but it mostly entailed dumping a bag of comma's on the text.
There are two things that I am not quite sure about, so I haven't (yet) changed them:
> Once the client knows the upload offset, it can send another PATCH request until the upload is completely down.
Is this sentence correct? What does 'down' mean here?
> If you are dealing with HTTP proxies that strip/modify HTTP headers or can't handle PATCH requests properly, you should consider using HTTPS. This will make it impossible for proxies to modify your requests and use the X-HTTP-Method-Override header which allows you to use POST requests.
The second sentence isn't completely clear to me. …

Another round of polish for the FAQ

---

assets/stylesheets/home.scss

I've received a Moblie Usablity alert from Google Search Console. Was checking how tus website works on mobile and noticed that on narrow screens a horizontal scrollbar might appear. Here are some small fixes to resolve it :)

Fix mobile issues

---

_includes/community.html

https://app.intercom.com/a/apps/qiqpfgjg/inbox/inbox/all/conversations/26852700005053 Removed kevin-openc as it was a broken link, couldnt find a replacement link and the bug researcher took it over.

removing kevin-openc

---

_data/logos.yml

Hi,
RANCH Computing has been using tus for some time now, this PR adds its logo.
However it will likely have no effect, since the current template only shows the first 5 logos (they are now 13):
https://github.com/tus/tus.io/blob/026a7fddf3bd6bed7fd067a76e660299f11ea42f/_content/home.html#L136
Should the template be updated to display more logos? (if no then the sentence `Do you also (plan to) use tus? Add your company` should be removed ^^)
---
PS: I also used tus for a personal file transfer and I documented my journey in a short blog post. Maybe you'll find it interesting:
https://log.pfad.fr/2021/receiving-large-file/

logo: add RANCH Computing

---

.github/workflows/ci.yml
src/components/RequestViewer.tsx

Otherwise build errors will not be visible in PRs. For example: https://github.com/tus/tus.io/actions/runs/5905861631/job/16020751357#step:7:175

Run `yarn build` in CI check for PRs

---

src/content/blog/2023-09-20-tusd-200.md

@kvz @AJvanLoon @Murderlon I invite you to have a read through this draft and let me know what you think!

Add blog post for tusd v2

---

.github/workflows/ci.yml
.github/workflows/deploy.yml

To fix the errors about yarn in recent CI runs. See https://transloadit.slack.com/archives/C034DSPA1/p1701684846910509 and https://github.com/tus/tus.io/actions/runs/7085115412/job/19280734208

Remove `cache: yarn`

---

src/lib/octokit.ts

CI is failing due to rate limits:
```
SecondaryRateLimit detected for request GET https://api.github.com/repositories/8825137/issues/comments?per_page=100&sort=created&direction=desc&page=30
error   You have exceeded a secondary rate limit. Please wait a few minutes before you try again. If you reach out to GitHub Support for help, please include the request ID 4000:3A7D64:2C3F768:537C37A:66A81D2A.
File:
src/pages/support.mdx
Stacktrace:
HttpError: You have exceeded a secondary rate limit. Please wait a few minutes before you try again. If you reach out to GitHub Support for help, please include the request ID 4000:3A7D64:2C3F768:537C37A:66A81D2A.
at /home/runner/work/tus.io/tus.io/node_modules/@octokit/request/dist-node/index.js:112:21
at process.processTicksAndRejections …
```

Fix rate limiting in CI build

---

src/pages/rss.xml.ts

Fixes this warning from the CI build:
```
λ src/pages/rss.xml.ts
06:36:13 AM [astro] Lower case endpoint names are deprecated and will not be supported in Astro 4.0. Rename the endpoint get to GET.
└─ /rss.xml (+14ms)
```

Fix warning about lower case HTTP method

---

src/pages/index.astro

A few changes to fix typos and make the copy on the front page read a little smoother.

Improve copy in index.astro

---

src/content/implementations/tuspyserver.json

Renamed references from "tuspy-fast-api" to "tuspyserver" in the JSON file to reflect the updated project name and repository link. This ensures consistency with the current naming and repository structure.
Changes come from the contribution: #https://github.com/edihasaj/tuspyserver/pull/58

Update implementation reference to tuspyserver
